### ISSUE TITLE
GitHub action failing

### ISSUE THREAD

**Issue by wragge** [frictionlessdata/frictionless-ci#47]
# Overview

I use the Frictionless GitHub action in a number of repositories to check datasets created updated on a weekly schedule. Today the action failed to run, generating the same error in all repositories:

```
 exec /bin/sh: no such file or directory
  The command '/bin/sh -c curl -fsSL https://deb.nodesource.com/setup_14.x | bash - &&   apt-get install -y nodejs &&   npm install --production &&   pip install -r requirements.txt' returned a non-zero code: 1
```

My workflow file contains:

``` yaml
name: frictionless

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Fetch latest data"]
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true # add this to download LFS files
          submodules: true # add this to download submodules
      - name: Validate data
        uses: frictionlessdata/repository@v1
```

I tried updating to `repository@v2` but that didn't help.

**Comment by ezwelty** [comment]
Exactly the same issue at https://github.com/mjacqu/glenglat

**Comment by dennisangemi** [comment]
Same problem here https://github.com/indecis-it/data/actions/runs/5454493998/jobs/9924691412#step:2:83

**Comment by roll** [comment]
FIXED

**Comment by dennisangemi** [comment]
Thx @roll !

Still failing for me ([see run](https://github.com/indecis-it/data/actions/runs/5518507375)); should I do something?

**Comment by roll** [comment]
Hi sorry for the confusion we're releasing the fix :+1:

**Comment by dennisangemi** [comment]
Thank you @roll ;)

**Comment by roll** [comment]
Can you please try it now?

I hope we fixed it. It was a really tricky problem in the middle of the docker images and similar matters

**Comment by dennisangemi** [comment]
@roll [this](https://github.com/indecis-it/data/actions/runs/5522674582/jobs/10072587386) is the run latest run. Now the docker seems to be working 🚀  thx!

Btw I don't know why my validation fails (the workflow file doesn't contain inquiry because there is a datapatackage.yaml file in the root of the repo). What do u think?

**Comment by roll** [comment]
@shashigharti 
Can you please take a look at https://github.com/indecis-it/data? :pray:

**Comment by shashigharti** [comment]
@dennisangemi new fix is updated and it should work now. Thanks!

**Comment by dennisangemi** [comment]
IT WORKS! 🚀🚀 ([see run](https://github.com/indecis-it/data/actions/runs/5586738464))
Thanks a lot @shashigharti and @roll ;)
